version: '2'
services:
  mochi:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: mochi
    ports:
     - "8081:8080"
    command: npm start
    environment:
      MOCHI_ENV: 'prod'
      COUCHDB_IP: 52.16.243.214
      COUCHDB_PORT: 5985
  couchdb:
    build:
      context: .
      dockerfile: Dockerfile.couchdb
    image: couchdb
    ports:
     - "5985:5984"
